[project]
name = "fast-api-project1"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "redis>=5.0.0",
    "alembic>=1.19.2",
    "asyncpg>=0.31.0",
    "bcrypt>=5.0.0",
    "fastapi[standard]>=0.141.1",
    "pydantic-settings>=2.15.0",
    "pyjwt>=2.13.0",
    "sqlmodel>=0.0.42",
    "uvicorn>=0.52.4",
    "fastapi-mail>=1.6.8",
    "passlib>=1.7.4",
    "itsdangerous>=2.2.0",
    "celery>=5.6.3",
    "asgiref>=3.12.1",
    "flower>=2.1.0",
    "pytest>=9.1.1",
    "schemathesis>=4.26.1",
]
